
version: '3'

services:
  db:
    container_name: "todo-db"
    build: ./docker/db
    ports:
      - "3306:3306"
    image: mysql:5.7
    volumes:
      - ./docker/db/scripts:/docker-entrypoint-initdb.d
      - ./docker/db/mysql_data:/var/lib/mysql
      # - ./docker/db/scripts:/killLifecycle.sh
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd!
    networks:
      - local

volumes:
    data-volume:

networks:
  local: