version: '2.2.3'

services:

  db:
      image: mysql:latest
      command: --default-authentication-plugin-mysql_native_password
      restart: always
      enviroment:
        MYSQL_ROOT_PASSWORD: P@ssw0rd!
      ports:
      - 3306:3306
      volumes:
      - "./todo/models/todo.sql"